export const userList = [
	{
		gender: "female",
		title: "Ms",
		first_name: "Janice",
		last_name: "Simmmons",
		number: 4878,
		name: "Harrison Ct",
		city: "Devonport",
		state: "Queensland",
		country: "Australia",
		postcode: 3753,
		latitude: "-83.9424",
		longitude: "128.6961",
		email: "janice.simmmons@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/78.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Elias",
		last_name: "Oja",
		number: 6356,
		name: "Rautatienkatu",
		city: "Leppävirta",
		state: "Central Ostrobothnia",
		country: "Finland",
		postcode: 64294,
		latitude: "-54.1731",
		longitude: "6.3359",
		email: "elias.oja@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/40.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Nelson",
		last_name: "Nichols",
		number: 1055,
		name: "Hogan St",
		city: "Fort Worth",
		state: "North Dakota",
		country: "United States",
		postcode: 17840,
		latitude: "47.2831",
		longitude: "44.2693",
		email: "nelson.nichols@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/80.jpg",
	},
	{
		gender: "female",
		title: "Mrs",
		first_name: "Deniz",
		last_name: "Süleymanoğlu",
		number: 9252,
		name: "Necatibey Cd",
		city: "Kahramanmaraş",
		state: "Trabzon",
		country: "Turkey",
		postcode: 90951,
		latitude: "-21.6358",
		longitude: "-60.3396",
		email: "deniz.suleymanoglu@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/19.jpg",
	},
	{
		gender: "male",
		title: "Monsieur",
		first_name: "Quentin",
		last_name: "Joly",
		number: 6383,
		name: "Rue du Dauphiné",
		city: "St. Margrethen",
		state: "Appenzell Ausserrhoden",
		country: "Switzerland",
		postcode: 1961,
		latitude: "38.0490",
		longitude: "123.1878",
		email: "quentin.joly@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/3.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Mustafa",
		last_name: "Balcı",
		number: 8202,
		name: "Necatibey Cd",
		city: "Balıkesir",
		state: "Kayseri",
		country: "Turkey",
		postcode: 24575,
		latitude: "-86.5965",
		longitude: "47.0491",
		email: "mustafa.balci@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/11.jpg",
	},
	{
		gender: "female",
		title: "Mrs",
		first_name: "Nurdan",
		last_name: "Çankaya",
		number: 2649,
		name: "Kushimoto Sk",
		city: "Afyonkarahisar",
		state: "Mersin",
		country: "Turkey",
		postcode: 15292,
		latitude: "24.8984",
		longitude: "112.6939",
		email: "nurdan.cankaya@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/58.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "پرنیا",
		last_name: "علیزاده",
		number: 2086,
		name: "میدان استقلال",
		city: "اهواز",
		state: "قزوین",
		country: "Iran",
		postcode: 74398,
		latitude: "-14.5861",
		longitude: "-129.0663",
		email: "prny.aalyzdh@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/89.jpg",
	},
	{
		gender: "female",
		title: "Mrs",
		first_name: "Emilie",
		last_name: "Jensen",
		number: 175,
		name: "Enghavevej",
		city: "København V",
		state: "Syddanmark",
		country: "Denmark",
		postcode: 10831,
		latitude: "54.7404",
		longitude: "124.2856",
		email: "emilie.jensen@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/2.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Christian",
		last_name: "Thomsen",
		number: 9116,
		name: "Langagervej",
		city: "Tisvilde",
		state: "Danmark",
		country: "Denmark",
		postcode: 57902,
		latitude: "-49.5814",
		longitude: "-167.7552",
		email: "christian.thomsen@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/83.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Joshua",
		last_name: "Green",
		number: 8306,
		name: "Gloucester Street",
		city: "Hamilton",
		state: "Gisborne",
		country: "New Zealand",
		postcode: 53371,
		latitude: "21.7797",
		longitude: "-49.8490",
		email: "joshua.green@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/93.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Donald",
		last_name: "Vargas",
		number: 9737,
		name: "Valwood Pkwy",
		city: "Odessa",
		state: "Montana",
		country: "United States",
		postcode: 64040,
		latitude: "83.0412",
		longitude: "133.1051",
		email: "donald.vargas@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/35.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "بردیا",
		last_name: "مرادی",
		number: 3275,
		name: "دکتر چمران",
		city: "اهواز",
		state: "سمنان",
		country: "Iran",
		postcode: 47998,
		latitude: "-40.9689",
		longitude: "113.8638",
		email: "brdy.mrdy@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/59.jpg",
	},
	{
		gender: "female",
		title: "Mrs",
		first_name: "Mia",
		last_name: "Robinson",
		number: 975,
		name: "Durham Street",
		city: "Hamilton",
		state: "West Coast",
		country: "New Zealand",
		postcode: 69728,
		latitude: "-51.9838",
		longitude: "165.4434",
		email: "mia.robinson@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/66.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Erica",
		last_name: "Garcia",
		number: 7473,
		name: "E North St",
		city: "Edison",
		state: "Mississippi",
		country: "United States",
		postcode: 61793,
		latitude: "18.5395",
		longitude: "11.3395",
		email: "erica.garcia@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/59.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Mike",
		last_name: "Ward",
		number: 1325,
		name: "James St",
		city: "Traralgon",
		state: "Victoria",
		country: "Australia",
		postcode: 2972,
		latitude: "82.3127",
		longitude: "155.4685",
		email: "mike.ward@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/28.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Yann",
		last_name: "Gautier",
		number: 5117,
		name: "Avenue Vauban",
		city: "Nîmes",
		state: "Ardennes",
		country: "France",
		postcode: 61789,
		latitude: "19.3662",
		longitude: "-94.9706",
		email: "yann.gautier@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/96.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Ralph",
		last_name: "Wright",
		number: 5486,
		name: "Spring St",
		city: "Devonport",
		state: "Victoria",
		country: "Australia",
		postcode: 8745,
		latitude: "-49.6717",
		longitude: "-110.1888",
		email: "ralph.wright@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/23.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Aaron",
		last_name: "Robinson",
		number: 53,
		name: "Barbadoes Street",
		city: "Hastings",
		state: "Hawke'S Bay",
		country: "New Zealand",
		postcode: 77221,
		latitude: "11.2098",
		longitude: "34.2611",
		email: "aaron.robinson@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/89.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Leah",
		last_name: "Banks",
		number: 3350,
		name: "W Belt Line Rd",
		city: "Sunshine Coast",
		state: "Victoria",
		country: "Australia",
		postcode: 6561,
		latitude: "57.1402",
		longitude: "176.5395",
		email: "leah.banks@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/75.jpg",
	},
	{
		gender: "female",
		title: "Ms",
		first_name: "Edelmira",
		last_name: "Gonçalves",
		number: 1867,
		name: "Rua Pará ",
		city: "Manaus",
		state: "Rio Grande do Sul",
		country: "Brazil",
		postcode: 87092,
		latitude: "6.2996",
		longitude: "177.1240",
		email: "edelmira.goncalves@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/37.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Veraldina",
		last_name: "Moraes",
		number: 9804,
		name: "Rua Pernambuco ",
		city: "Cabo Frio",
		state: "Rio de Janeiro",
		country: "Brazil",
		postcode: 72345,
		latitude: "24.4232",
		longitude: "-23.9403",
		email: "veraldina.moraes@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/44.jpg",
	},
	{
		gender: "female",
		title: "Mrs",
		first_name: "Ria",
		last_name: "Eitel",
		number: 7387,
		name: "Finkenweg",
		city: "Holzminden",
		state: "Berlin",
		country: "Germany",
		postcode: 92912,
		latitude: "-78.5615",
		longitude: "78.4522",
		email: "ria.eitel@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/37.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Mathias",
		last_name: "Madsen",
		number: 1221,
		name: "Kærsangervej",
		city: "Vipperød",
		state: "Sjælland",
		country: "Denmark",
		postcode: 58177,
		latitude: "70.2432",
		longitude: "121.1022",
		email: "mathias.madsen@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/18.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first: "شایان_name",
		last: "سهيلي_name راد",
		number: 3268,
		name: "آیت الله سعیدی",
		city: "اردبیل",
		state: "اصفهان",
		country: "Iran",
		postcode: 41972,
		latitude: "83.9872",
		longitude: "-42.9795",
		email: "shyn.shylyrd@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/95.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "James",
		last_name: "Addy",
		number: 7011,
		name: "Regent Ave",
		city: "Stirling",
		state: "Alberta",
		country: "Canada",
		postcode: "K4V 0K8",
		latitude: "-44.8101",
		longitude: "117.3696",
		email: "james.addy@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/74.jpg",
	},
	{
		gender: "female",
		title: "Ms",
		first_name: "Denise",
		last_name: "Fütterer",
		number: 7722,
		name: "Kirchweg",
		city: "Rügen",
		state: "Bayern",
		country: "Germany",
		postcode: 35533,
		latitude: "-50.0594",
		longitude: "164.6066",
		email: "denise.futterer@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/73.jpg",
	},
	{
		gender: "female",
		title: "Ms",
		first_name: "Julia",
		last_name: "Maijala",
		number: 576,
		name: "Reijolankatu",
		city: "Janakkala",
		state: "Southern Ostrobothnia",
		country: "Finland",
		postcode: 87326,
		latitude: "8.3613",
		longitude: "-9.1410",
		email: "julia.maijala@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/3.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Sigve",
		last_name: "Dalhaug",
		number: 437,
		name: "Glitreveien",
		city: "Søre Øyane",
		state: "Akershus",
		country: "Norway",
		postcode: "9064",
		latitude: "68.0342",
		longitude: "-78.0114",
		email: "sigve.dalhaug@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/67.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Logan",
		last_name: "Ellis",
		number: 9233,
		name: "O'Connell Avenue",
		city: "Bray",
		state: "Clare",
		country: "Ireland",
		postcode: 56452,
		latitude: "-60.2892",
		longitude: "-7.5791",
		email: "logan.ellis@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/97.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Joey",
		last_name: "Reed",
		number: 8558,
		name: "Grange Road",
		city: "St Albans",
		state: "Merseyside",
		country: "United Kingdom",
		postcode: "F9E 3XX",
		latitude: "10.2272",
		longitude: "-147.3308",
		email: "joey.reed@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/39.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Terrence",
		last_name: "Jones",
		number: 3651,
		name: "Frances Ct",
		city: "Cedar Hill",
		state: "Virginia",
		country: "United States",
		postcode: 21079,
		latitude: "-61.3572",
		longitude: "-0.0777",
		email: "terrence.jones@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/75.jpg",
	},
	{
		gender: "female",
		title: "Ms",
		first_name: "Noémie",
		last_name: "Macdonald",
		number: 6815,
		name: "St. Lawrence Ave",
		city: "Beaumont",
		state: "Manitoba",
		country: "Canada",
		postcode: "J1U 2A0",
		latitude: "8.7985",
		longitude: "47.1558",
		email: "noemie.macdonald@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/51.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Cecilie",
		last_name: "Jørgensen",
		number: 2380,
		name: "Hjulets Kvarter",
		city: "Snertinge",
		state: "Syddanmark",
		country: "Denmark",
		postcode: 75900,
		latitude: "-27.1304",
		longitude: "-145.8728",
		email: "cecilie.jorgensen@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/82.jpg",
	},
	{
		gender: "female",
		title: "Ms",
		first_name: "Cristina",
		last_name: "Fernandez",
		number: 8125,
		name: "Calle de Toledo",
		city: "Córdoba",
		state: "Ceuta",
		country: "Spain",
		postcode: 52903,
		latitude: "3.0477",
		longitude: "-35.7743",
		email: "cristina.fernandez@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/47.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Jacob",
		last_name: "Johnson",
		number: 4676,
		name: "St Aubyn Street",
		city: "Tauranga",
		state: "Tasman",
		country: "New Zealand",
		postcode: 97102,
		latitude: "62.4406",
		longitude: "133.6138",
		email: "jacob.johnson@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/63.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Adelheid",
		last_name: "Nikolaus",
		number: 8733,
		name: "Schulstraße",
		city: "Bendorf",
		state: "Niedersachsen",
		country: "Germany",
		postcode: 29709,
		latitude: "-87.1293",
		longitude: "-178.1335",
		email: "adelheid.nikolaus@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/31.jpg",
	},
	{
		gender: "female",
		title: "Mrs",
		first_name: "Montserrat",
		last_name: "Guerrero",
		number: 9840,
		name: "Calle de Arturo Soria",
		city: "Málaga",
		state: "Galicia",
		country: "Spain",
		postcode: 65162,
		latitude: "88.4657",
		longitude: "-171.5360",
		email: "montserrat.guerrero@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/60.jpg",
	},
	{
		gender: "female",
		title: "Ms",
		first_name: "Afşar",
		last_name: "Hakyemez",
		number: 4714,
		name: "Tunalı Hilmi Cd",
		city: "Edirne",
		state: "Niğde",
		country: "Turkey",
		postcode: 18946,
		latitude: "-69.5388",
		longitude: "-70.2220",
		email: "afsar.hakyemez@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/13.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Lea",
		last_name: "Pedersen",
		number: 4560,
		name: "Christian Winthers Vej",
		city: "Samsø",
		state: "Danmark",
		country: "Denmark",
		postcode: 58832,
		latitude: "33.6667",
		longitude: "-116.7951",
		email: "lea.pedersen@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/90.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Nick",
		last_name: "Lord",
		number: 243,
		name: "Highfield Road",
		city: "Stirling",
		state: "Central",
		country: "United Kingdom",
		postcode: "J1 2HD",
		latitude: "-22.6268",
		longitude: "98.1878",
		email: "nick.lord@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/87.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Megan",
		last_name: "Tremblay",
		number: 9317,
		name: "Regent Ave",
		city: "Princeton",
		state: "Alberta",
		country: "Canada",
		postcode: "X1N 7Q7",
		latitude: "65.3142",
		longitude: "78.7201",
		email: "megan.tremblay@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/50.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Juliane",
		last_name: "Brandal",
		number: 4182,
		name: "Heggelibakken",
		city: "Bjervamoen",
		state: "Buskerud",
		country: "Norway",
		postcode: "5704",
		latitude: "-83.2563",
		longitude: "172.3197",
		email: "juliane.brandal@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/10.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Esmiralda",
		last_name: "Plet",
		number: 3811,
		name: "Ganzerikpad",
		city: "Werkhoven",
		state: "Flevoland",
		country: "Netherlands",
		postcode: 45770,
		latitude: "73.4011",
		longitude: "116.0941",
		email: "esmiralda.plet@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/49.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "میلاد",
		last_name: "حسینی",
		number: 1428,
		name: "میرداماد",
		city: "ملارد",
		state: "یزد",
		country: "Iran",
		postcode: 39607,
		latitude: "-3.1562",
		longitude: "-161.2898",
		email: "myld.hsyny@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/37.jpg",
	},
	{
		gender: "female",
		title: "Miss",
		first_name: "Bettina",
		last_name: "Tonheim",
		number: 3512,
		name: "Salmakersvenn Marius Jantzens plass",
		city: "Nesna",
		state: "Troms - Romsa",
		country: "Norway",
		postcode: "0687",
		latitude: "-38.0868",
		longitude: "-48.5755",
		email: "bettina.tonheim@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/women/9.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Luis",
		last_name: "Burke",
		number: 2369,
		name: "Adams St",
		city: "Melbourne",
		state: "Victoria",
		country: "Australia",
		postcode: 5252,
		latitude: "-40.8467",
		longitude: "127.9244",
		email: "luis.burke@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/46.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Philippe",
		last_name: "Lo",
		number: 3679,
		name: "Vimy St",
		city: "Keswick",
		state: "British Columbia",
		country: "Canada",
		postcode: "Q2E 9Y2",
		latitude: "24.7638",
		longitude: "-165.9110",
		email: "philippe.lo@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/9.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Dennis",
		last_name: "Peters",
		number: 4337,
		name: "Country Club Rd",
		city: "Richardson",
		state: "Vermont",
		country: "United States",
		postcode: 97572,
		latitude: "-48.7342",
		longitude: "-171.5279",
		email: "dennis.peters@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/53.jpg",
	},
	{
		gender: "male",
		title: "Mr",
		first_name: "Varg",
		last_name: "Krane",
		number: 9193,
		name: "Bestemorstien",
		city: "Fauske",
		state: "Trøndelag",
		country: "Norway",
		postcode: "4156",
		latitude: "-59.5551",
		longitude: "102.0272",
		email: "varg.krane@example.com",
		profileImage: "https://randomuser.me/api/portraits/med/men/3.jpg",
	}
];

export const filter_companies = [
	{ label: 'All', value: 'all' }, 
	{ label : ' - User without company', value :  'no_company'},
	{ value: 'Mastercard', label : 'Mastercard' },
	{ value: 'Facebook', label : 'Facebook' },
	{ value: 'Nintendo', label : 'Nintendo' }
];


  
